server:
  port:
    8082

spring:
  datasource:
    driverClassName:
      com.mysql.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/stocks?allowPublicKeyRetrieval=true&useSSL=false
    username:
      dbuser
    password:
      dbpassword

  jackson:
    serialization:
      fail-on-empty-beans:
        false

  jpa:
    generate-ddl:
      true
    hibernate:
      ddl-auto:
        create
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: local

dataset-url:
  https://bootcamp-training-files.cfapps.io/week4/week4_stocks.json
